# Generated by Django 6.0.4 on 2026-04-25 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_otp_enabled_user_otp_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp_enabled',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp_secret',
        ),
    ]
