# Generated by Django 6.0.4 on 2026-04-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_user_otp_enabled_remove_user_otp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Format international sans + ni espaces. Ex: 212612345678 (Maroc), 33612345678 (France)', max_length=20, null=True, unique=True, verbose_name='Numéro WhatsApp'),
        ),
    ]
