# Generated by Django 6.0.4 on 2026-04-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='whatsapp_lid',
            field=models.CharField(blank=True, help_text='Identifiant interne @lid. Visible dans les logs : [RESOLVE] numéro normalisé = XXXXXXX', max_length=50, null=True, unique=True, verbose_name='WhatsApp LID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Format international sans + ni espaces. Ex: 212612345678', max_length=20, null=True, unique=True, verbose_name='Numéro WhatsApp'),
        ),
    ]
