# Generated by Django 6.0.4 on 2026-04-22 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0002_alter_invoice_company_remove_facture_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='devise',
            field=models.CharField(choices=[('MAD', 'Dirham marocain'), ('EUR', 'Euro'), ('USD', 'Dollar américain'), ('GBP', 'Livre sterling'), ('AED', 'Dirham émirati'), ('SAR', 'Riyal saoudien'), ('CHF', 'Franc suisse'), ('CAD', 'Dollar canadien'), ('JPY', 'Yen japonais'), ('CNY', 'Yuan chinois')], default='MAD', max_length=3),
        ),
    ]
