# Generated by Django 6.0.4 on 2026-04-27 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_whatsapp_lid_alter_user_phone'),
        ('factures', '0003_invoice_devise'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_ref', models.CharField(blank=True, help_text='Référence conservée même si la facture est supprimée', max_length=100)),
                ('user_email', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(choices=[('CREATED', 'Créée'), ('VALIDATED', 'Validée'), ('REJECTED', 'Rejetée'), ('DELETED', 'Supprimée'), ('UPLOADED', 'Uploadée'), ('EXPORTED', 'Exportée'), ('DUPLICATE', 'Doublon détecté')], max_length=20)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='authentication.company')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='factures.invoice')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journal d'audit",
                'ordering': ['-created_at'],
            },
        ),
    ]
