# Generated by Django 6.0.4 on 2026-04-30 20:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_user_avatar'),
        ('factures', '0004_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='numero_facture',
            field=models.CharField(blank=True, help_text='Numéro de facture du fournisseur', max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['company', 'fournisseur', 'date_facture', 'total'], name='factures_in_company_a4bca6_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['company', 'numero_facture'], name='factures_in_company_7c2294_idx'),
        ),
    ]
