# Generated by Django 6.0.4 on 2026-05-01 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0005_invoice_numero_facture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
